use_frameworks!

platform :ios, '9.0'

target 'Shield_Example' do
  pod 'Shield', :path => '../'
end

post_install do |installer|
  
  puts 'Disable CODE_SIGNING_ALLOWED for Xcode 14'
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
  
end
